# version: '3.8'
services:
  app2:
    build:
      dockerfile: Dockerfile
      context: .
    # コンテナを起動したままにする
    tty: true
    # command: /bin/sh -c "yarn install && apt install -y libwebkit2gtk-4.1-dev  && yarn tauri dev"
    # command: /bin/sh -c "yarn install  && yarn dev"
    # command: /bin/sh -c "yarn install  && yarn tauri dev"
    environment:
      # ホストのディスプレイ設定をコンテナに渡す
      # windows
      # - DISPLAY=$DISPLAY
      # mac
      - DISPLAY=host.docker.internal:0
      # - WAYLAND_DISPLAY=$WAYLAND_DISPLAY
      # XDGランタイムディレクトリを設定
      - XDG_RUNTIME_DIR=/tmp
      # PulseAudioサーバーの設定を渡す
      # - PULSE_SERVER=$PULSE_SERVER
      - LANG=ja_JP.UTF-8 
      - LC_ALL=ja_JP.UTF-8
      - LIBGL_ALWAYS_SOFTWARE=1  # ソフトウェアレンダリングを強制
    volumes:
      - ./remind:/app
      # X11ソケットをマウント（X11でのGUI表示用）
      - type: bind
        # windows
        # source: /tmp/.X11-unix
        # target: /tmp/.X11-unix
        # mac
        source: $HOME/.Xauthority  # X11認証情報のマウント
        target: /root/.Xauthority  # コンテナ内での位置
    ports:
      - "1420:1420"
      - "3000:3000"
      - "8080:8080"
      # Waylandソケットをマウント（Waylandでのディスプレイ用）
      # - type: bind
      #   source: "${XDG_RUNTIME_DIR}/wayland-0"
      #   target: /tmp/wayland-0

  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./tauri:/app
  #     - ./sqlite_data:/app/data
  #     # create app後にコメントを外す
  #     - node_modules:/app/node_modules

  #   ports:
  #     - "1420:1420"
  #     - "3000:3000"
  #     - "8080:8080"
  #   environment:
  #     - DISPLAY=${DISPLAY}
  #   # network_mode: host
  #   # command: /bin/sh -c "yarn install && yarn tauri dev"
  #   tty: true
  #   user: "${UID}:${GID}"
  #   # depends_on:
    #   - db

  # db:
  #   image: postgres:13
  #   environment:
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_DB: mydb
  #   ports:
  #     - "5432:5432"

volumes:
  node_modules:
  # sqlite_data:
